# -*- coding: utf-8 -*-
"""Deep_Learning_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xx9W3IUtVbCrLSn3x-rgIm5RtilYcm9r

# Deep Learning - Project 4: Few-shot Learning with Siamese Networks

Students: Elly Delaplace,Rawan Kazma, Nicolas Xanthakis

## Import packages
"""

import matplotlib.pyplot as plt
import numpy as np
import torch
import os
from PIL import Image
import json
from glob import glob
from google.colab import drive
import random
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import pandas as pd
import seaborn as sns
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, datasets
from sklearn.metrics import average_precision_score
import wandb
import shutil
import time
import torchvision

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(DEVICE)

drive.mount('/content/drive')

"""## Data Preprocessing

#### Data Loading
"""

ROOT_DATA_PATH = "/content/drive/MyDrive/DL Project/Data"

TRAIN_SPLIT_FOLDER = "train_resized"
TEST_SPLIT_FOLDER = "test_resized"

train_path = os.path.join(ROOT_DATA_PATH, TRAIN_SPLIT_FOLDER)
test_path = os.path.join(ROOT_DATA_PATH, TEST_SPLIT_FOLDER)

"""#### Data splitting"""

# New output folders for the class-disjoint split
TRAIN_OUTPUT_FOLDER = "train_split"
TEST_OUTPUT_FOLDER = "test_split"
train_path = os.path.join(ROOT_DATA_PATH, TRAIN_OUTPUT_FOLDER)
test_path = os.path.join(ROOT_DATA_PATH, TEST_OUTPUT_FOLDER)


# Class split counts
RANDOM_SEED = 42 # Necessary for reproducibility
TRAIN_COUNT = 80
TEST_COUNT = 20
TOTAL_CLASSES = TRAIN_COUNT + TEST_COUNT

def create_data_splits(root_data_path):
    """
    Performs a class-disjoint split (80 train classes, 20 test classes)
    and physically copies the images into new directory structures.
    """
    random.seed(RANDOM_SEED)

    # Output Directories
    train_path = os.path.join(root_data_path, TRAIN_OUTPUT_FOLDER)
    test_path = os.path.join(root_data_path, TEST_OUTPUT_FOLDER)

    if os.path.exists(train_path) and os.path.exists(test_path):
      print("Split already happened for you")
      return

    # 1. Determine all unique class names
    class_folders_path = os.path.join(root_data_path, TRAIN_SPLIT_FOLDER)
    if not os.path.exists(class_folders_path):
        raise FileNotFoundError(f"Source folder not found: {class_folders_path}. Check ROOT_DATA_PATH.")

    all_entries = os.listdir(class_folders_path)
    all_classes = sorted([entry for entry in all_entries if os.path.isdir(os.path.join(class_folders_path, entry)) and not entry.startswith('.')])

    if len(all_classes) != TOTAL_CLASSES:
        print(f"WARNING: Found {len(all_classes)} classes, but expected {TOTAL_CLASSES}. Proceeding with found classes.")

    # 2. Perform random class split
    shuffled_classes = all_classes[:]
    random.shuffle(shuffled_classes)

    train_classes = set(shuffled_classes[:TRAIN_COUNT])
    test_classes = set(shuffled_classes[TRAIN_COUNT:])

    os.makedirs(train_path, exist_ok=True)
    os.makedirs(test_path, exist_ok=True)

    # 3. Copy files to new split folders
    splits_counts = {'train': 0, 'test': 0}

    class_to_output_path = {}
    for cl in train_classes: class_to_output_path[cl] = os.path.join(train_path, cl)
    for cl in test_classes: class_to_output_path[cl] = os.path.join(test_path, cl)

    # Loop through the two source data folders to gather all images
    for data_folder_name in [TRAIN_SPLIT_FOLDER, TEST_SPLIT_FOLDER]:
        current_data_path = os.path.join(root_data_path, data_folder_name)

        for class_label in all_classes:
            output_class_path = class_to_output_path.get(class_label)
            if not output_class_path:
                continue

            # Create the class folder in the new split directory
            os.makedirs(output_class_path, exist_ok=True)

            # Find all image files in the source class folder
            class_path_source = os.path.join(current_data_path, class_label)

            exts = ["JPEG"]
            image_paths = []
            for ext in exts:
                image_paths.extend(glob(os.path.join(class_path_source, f"*.{ext}")))

            # Copy the files
            set_name = 'train' if class_label in train_classes else 'test'
            for path in image_paths:
                try:
                    # Use the base filename to avoid path conflicts
                    destination_path = os.path.join(output_class_path, os.path.basename(path))
                    shutil.copy2(path, destination_path)
                    splits_counts[set_name] += 1
                except Exception as e:
                    print(f"Error copying file {path}: {e}")

# Execution Block
if __name__ == '__main__':

    print("Starting physical data splitting...")
    create_data_splits(ROOT_DATA_PATH)
    print("Data splitting finished.")

"""#### Data exploration"""

def analyze_split(root_path):
    results = {}

    for subset in ["train_split", "test_split"]:
        subset_path = os.path.join(root_path, subset)
        if not os.path.exists(subset_path):
            raise FileNotFoundError(f"{subset_path} does not exist")

        # Class folders
        classes = sorted([d for d in os.listdir(subset_path) if os.path.isdir(os.path.join(subset_path, d)) and not d.startswith(".")])

        # Count samples
        num_samples = 0
        for cls in classes:
            cls_path = os.path.join(subset_path, cls)
            num_samples += len(glob(os.path.join(cls_path, "*.JPEG")))

        results[subset] = {"num_classes": len(classes),
                           "num_samples": num_samples,
                           "classes": classes}

    for subset, info in results.items():
        name = "train" if subset == "train_split" else "test"
        print(f"\n{name.upper()} SET")
        print(f"Number of classes: {info['num_classes']}")
        print(f"Number of samples: {info['num_samples']}")
        print(f"Classes: {info['classes']}")

# EXECUTION
analyze_split(ROOT_DATA_PATH)

# Visualization
samples = []
for cls in os.listdir(train_path):
    cls_path = os.path.join(train_path, cls)
    if os.path.isdir(cls_path):
        for img in glob(os.path.join(cls_path, "*.JPEG")):
            samples.append((img, cls))

# Randomly select 10 samples
sampled = random.sample(samples, 10)

# Plot
fig, axes = plt.subplots(2, 5, figsize=(20, 8))
axes = axes.flatten()

for ax, (img_path, label) in zip(axes, sampled):
    img = Image.open(img_path).convert("RGB")
    ax.imshow(img)
    ax.set_title(label)
    ax.axis("off")

plt.tight_layout()
plt.show()

"""## Siamese Network: Custom CNN

#### Model 1: Contrastive loss
"""

########################################
#########  DATA TRANSFORMS   ###########
########################################

train_transform = transforms.Compose([transforms.RandomResizedCrop(size=224, scale=(0.8, 1.0)),
                                      transforms.RandomHorizontalFlip(),
                                      transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.1),
                                      transforms.RandomApply([transforms.GaussianBlur(kernel_size=(3,3))], p=0.2),
                                      transforms.ToTensor(),
                                      transforms.Normalize(mean=[0.5,0.5,0.5], std=[0.5,0.5,0.5])])

test_transform = transforms.Compose([transforms.ToTensor(),
                                     transforms.Normalize(mean=[0.5,0.5,0.5], std=[0.5,0.5,0.5])])

########################################
##########  CUSTOM DATASET   ###########
########################################

class ContrastiveDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        # ImageFolder reads your folder structure automatically
        self.base_dataset = datasets.ImageFolder(root=root_dir, transform=transform)
        self.labels = np.array(self.base_dataset.targets)

        # Group indices by class
        self.class_indices = {}
        for idx, label in enumerate(self.labels):
            self.class_indices.setdefault(label, []).append(idx)

        self.unique_classes = list(self.class_indices.keys())

    def __len__(self):
        return len(self.base_dataset)

    def __getitem__(self, index):
        # Anchor
        img1, label1 = self.base_dataset[index]

        if random.random() < 0.5:
            # POSITIVE pair (same class): 1
            pair_label = torch.tensor(1.0)
            idx2 = index
            while idx2 == index:
                idx2 = random.choice(self.class_indices[label1])
        else:
            # NEGATIVE pair (different class): 0
            pair_label = torch.tensor(0.0)
            neg_class = random.choice([c for c in self.unique_classes if c != label1])
            idx2 = random.choice(self.class_indices[neg_class])

        img2, _ = self.base_dataset[idx2]

        return img1, img2, pair_label

contrastive_train_dataset = ContrastiveDataset(root_dir=train_path, transform=train_transform)

# Visualisation
# Denormalization function for [-1,1] normalized images
def denormalize(img_tensor):
    if isinstance(img_tensor, torch.Tensor):
        img_tensor = img_tensor.clone()
        img_tensor = img_tensor * 0.5 + 0.5  # Undo normalization
        img_tensor = img_tensor.clamp(0, 1)  # Ensure values are in [0,1]
    return img_tensor

# Sample 5 random indices from the dataset
indices = random.sample(range(len(contrastive_train_dataset)), 5)

fig, axes = plt.subplots(5, 2, figsize=(10, 20))

for i, idx in enumerate(indices):
    img1, img2, pair_label = contrastive_train_dataset[idx]

    # Plot anchor
    axes[i, 0].imshow(denormalize(img1).permute(1,2,0))
    axes[i, 0].set_title("Anchor")
    axes[i, 0].axis("off")

    # Plot pair
    axes[i, 1].imshow(denormalize(img2).permute(1,2,0))
    axes[i, 1].set_title(f"Pair label: {int(pair_label.item())}")
    axes[i, 1].axis("off")

plt.tight_layout()
plt.show()

#########################################
#########  CONTRASTIVE LOSS   ###########
#########################################

def contrastive_loss(embedding_1, embedding_2, label, margin=1.0):
    # label=0 if same class, 1 if different
    distance = F.pairwise_distance(embedding_1, embedding_2) # Euclidian distance between vectors

    loss_same = (1 - label) * torch.pow(distance, 2)
    loss_diff = label * torch.pow(torch.clamp(margin - distance, min=0.0), 2)

    return torch.mean(loss_same + loss_diff) #, dim = 0

######################################
##########   CUSTOM CNN   ############
######################################

class ContrastiveCustomCNN(nn.Module):
    def __init__(self):
        super(ContrastiveCustomCNN, self).__init__()

        # Block 1:
        # (BS, 3 x 224 x 224) (BS = Batch size)
        self.conv_block1 = nn.Sequential(nn.Conv2d(in_channels=3, out_channels=64, kernel_size=3, stride=1, padding=1),
                                    nn.BatchNorm2d(64),
                                    nn.ReLU(),
                                    nn.MaxPool2d(kernel_size=2, stride=2))

        # Block 2:
        # (BS x 128 x 112 x 112)
        self.conv_block2 = nn.Sequential(nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, stride=1, padding=1),
                                    nn.BatchNorm2d(128),
                                    nn.ReLU(),
                                    nn.MaxPool2d(kernel_size=2, stride=2))

        # Block 3:
        # (BS x 256 x 56 x 56)
        self.conv_block3 = nn.Sequential(nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, stride=1, padding=1),
                                    nn.BatchNorm2d(256),
                                    nn.ReLU(),
                                    nn.MaxPool2d(kernel_size=2, stride=2))

        # Block 4:
        # (BS x 256 x 28 x 28)
        self.conv_block4 = nn.Sequential(nn.Conv2d(in_channels=256, out_channels=256, kernel_size=3, stride=1, padding=1),
                                    nn.BatchNorm2d(256),
                                    nn.ReLU(),
                                    nn.MaxPool2d(kernel_size=2, stride=2))

        # Global average pooling:
        # (BS x 256 x 1 x 1)
        self.global_avg_pool = nn.AdaptiveAvgPool2d((1, 1))

        # Full connected layer
        self.fc = nn.Linear(256, 256)

        self.final_activation = nn.Sigmoid()

    def forward(self, x):
        x = self.conv_block1(x)
        x = self.conv_block2(x)
        x = self.conv_block3(x)
        x = self.conv_block4(x)

        x = self.global_avg_pool(x)
        x = x.view(x.size(0), -1) # (BS x 512)

        x = self.fc(x)

        embedding = self.final_activation(x)

        normalized_embedding = F.normalize(embedding, p=2, dim=1)

        return normalized_embedding

# CREATE INSTANCE OF THE MODEL
contrastive_model = ContrastiveCustomCNN()
contrastive_model = contrastive_model.to(DEVICE)
print(contrastive_model)

####################################
##########   TRAINING   ############
####################################

# Training hyperparameters
num_epochs = 30
learning_rate = 1e-3
batch_size = 64
num_workers = 4

# Optimizer
optimizer = optim.Adam(contrastive_model.parameters(), lr=learning_rate)

train_loader = DataLoader(dataset=contrastive_train_dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=True)

# Start a new wandb run to track this script
run = wandb.init(entity="elly-delaplace-universiteit-gent",
                 project="Deep_Learning_Project",
                 name="RUN 1 - 12/12/2025",
                 config={"architecture": "CustomSiameseCNN",
                         "loss_fn": "Contrastive Loss",
                         "batch_size": train_loader.batch_size,
                         "epochs": num_epochs,
                         "learning_rate": optimizer.param_groups[0]['lr'],
                         "train_samples": len(train_loader.dataset)})

# Training loop
def train_contrastive_SN(model, train_loader, optimizer, device, num_epochs=30):
    model.to(device)
    start_time = time.time()

    for epoch in range(num_epochs):
        print(f"\nEpoch [{epoch+1}/{num_epochs}]")
        model.train()
        running_loss = 0.0

        for batch_idx, (img1, img2, label) in enumerate(train_loader):
            img1, img2, label = img1.to(device), img2.to(device), label.to(device)

            optimizer.zero_grad()

            emb1 = model(img1)
            emb2 = model(img2)

            loss = contrastive_loss(emb1, emb2, label)

            loss.backward()
            optimizer.step()

            running_loss += loss.item()

        # Average loss over the epoch
        epoch_loss = running_loss / len(train_loader)

        # Log to W&B
        wandb.log({"train/contrastive_epoch_loss": epoch_loss})

        print(f"Epoch [{epoch+1}/{num_epochs}] - Contrastive Loss: {epoch_loss:.4f}")

    end_time = time.time()
    print("Training completed!")

    return end_time - start_time

train_contrastive_SN(contrastive_model, train_loader, optimizer, DEVICE, num_epochs=num_epochs)

"""#### Model 2: Triplet loss"""

########################################
##########  TRIPLET DATASET  ###########
########################################

class TripletDataset(Dataset):
    def __init__(self, root_dir, transform=None):
        self.base_dataset = datasets.ImageFolder(root=root_dir, transform=transform)
        self.labels = np.array(self.base_dataset.targets)

        self.class_indices = {}
        for idx, label in enumerate(self.labels):
            self.class_indices.setdefault(label, []).append(idx)

        self.unique_classes = list(self.class_indices.keys())

    def __len__(self):
        return len(self.base_dataset)

    def __getitem__(self, index):
        # 1. Anker (A)
        img_A, label_A = self.base_dataset[index]

        # 2. Positief (P)
        # P moet van dezelfde klasse zijn als A, maar een andere afbeelding.
        positive_indices = self.class_indices[label_A]
        valid_positive_indices = [i for i in positive_indices if i != index]
        idx_P = random.choice(valid_positive_indices)
        img_P, _ = self.base_dataset[idx_P]


        # 3. Negatief (N)
        # N moet van een andere klasse zijn dan A.
        neg_class = random.choice([c for c in self.unique_classes if c != label_A])
        idx_N = random.choice(self.class_indices[neg_class])
        img_N, _ = self.base_dataset[idx_N]

        # Retourneer het triplet (Anker, Positief, Negatief)
        return img_A, img_P, img_N

triplet_train_dataset = TripletDataset(root_dir=train_path, transform=train_transform)

# Visualization
# Sample 5 random indices
indices = random.sample(range(len(triplet_train_dataset)), 5)

fig, axes = plt.subplots(5, 3, figsize=(12, 15))

for i, idx in enumerate(indices):
    img_A, img_P, img_N = triplet_train_dataset[idx]

    axes[i, 0].imshow(denormalize(img1))
    axes[i, 0].set_title("Anchor")
    axes[i, 0].axis("off")

    axes[i, 1].imshow(denormalize(img_P))
    axes[i, 1].set_title("Positive")
    axes[i, 1].axis("off")

    axes[i, 2].imshow(denormalize(img_N))
    axes[i, 2].set_title("Negative")
    axes[i, 2].axis("off")

plt.tight_layout()
plt.show()

#####################################
#########  TRIPLET LOSS   ###########
#####################################

def triplet_loss(anchor, positive, negative, margin=1.0):

    dist_pos = F.pairwise_distance(anchor, positive)
    dist_neg = F.pairwise_distance(anchor, negative)
    triplet_loss = max(0, dist_pos - dist_neg + margin)

    return torch.mean(triplet_loss) # dim = 0

class TripletCustomCNN(nn.Module):
    def __init__(self):
        super(ContrastiveCustomCNN, self).__init__()

        # Block 1:
        # (BS, 3 x 224 x 224) (BS = Batch size)
        self.conv_block1 = nn.Sequential(nn.Conv2d(in_channels=3, out_channels=64, kernel_size=3, stride=1, padding=1),
                                    nn.BatchNorm2d(64),
                                    nn.ReLU(),
                                    nn.MaxPool2d(kernel_size=2, stride=2))

        # Block 2:
        # (BS x 128 x 112 x 112)
        self.conv_block2 = nn.Sequential(nn.Conv2d(in_channels=64, out_channels=128, kernel_size=3, stride=1, padding=1),
                                    nn.BatchNorm2d(128),
                                    nn.ReLU(),
                                    nn.MaxPool2d(kernel_size=2, stride=2))

        # Block 3:
        # (BS x 256 x 56 x 56)
        self.conv_block3 = nn.Sequential(nn.Conv2d(in_channels=128, out_channels=256, kernel_size=3, stride=1, padding=1),
                                    nn.BatchNorm2d(256),
                                    nn.ReLU(),
                                    nn.MaxPool2d(kernel_size=2, stride=2))

        # Block 4:
        # (BS x 256 x 28 x 28)
        self.conv_block4 = nn.Sequential(nn.Conv2d(in_channels=256, out_channels=256, kernel_size=3, stride=1, padding=1),
                                    nn.BatchNorm2d(256),
                                    nn.ReLU(),
                                    nn.MaxPool2d(kernel_size=2, stride=2))

        # Global average pooling:
        # (BS x 256 x 1 x 1)
        self.global_avg_pool = nn.AdaptiveAvgPool2d((1, 1))

        # Full connected layer
        self.fc = nn.Linear(256, 256)

        self.final_activation = nn.Sigmoid()

    def forward(self, x):
        x = self.conv_block1(x)
        x = self.conv_block2(x)
        x = self.conv_block3(x)
        x = self.conv_block4(x)

        x = self.global_avg_pool(x)
        x = x.view(x.size(0), -1) # (BS x 512)

        x = self.fc(x)

        embedding = self.final_activation(x)

        normalized_embedding = F.normalize(embedding, p=2, dim=1)

        return normalized_embedding

# CREATE INSTANCE OF THE MODEL
triplet_model = TripletCustomCNN()
triplet_model = triplet_model.to(DEVICE)
print(triplet_model)

####################################
##########   TRAINING   ############
####################################

# Training hyperparameters
num_epochs = 30
learning_rate = 1e-3
batch_size = 64
num_workers = 4

# Optimizer
optimizer = optim.Adam(triplet_model.parameters(), lr=learning_rate)

train_loader = DataLoader(dataset=triplet_train_dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=True)

# Start a new wandb run to track this script
run = wandb.init(entity="elly-delaplace-universiteit-gent",
                 project="Deep_Learning_Project",
                 name="RUN 1 - 12/12/2025",
                 config={"architecture": "CustomSiameseCNN",
                         "loss_fn": "Contrastive Loss",
                         "batch_size": train_loader.batch_size,
                         "epochs": num_epochs,
                         "learning_rate": optimizer.param_groups[0]['lr'],
                         "train_samples": len(train_loader.dataset)})

# Training loop
def train_contrastive_SN(model, train_loader, optimizer, device, num_epochs=30):
    model.to(device)
    start_time = time.time()

    for epoch in range(num_epochs):
        print(f"\nEpoch [{epoch+1}/{num_epochs}]")
        model.train()
        running_loss = 0.0

        for batch_idx, (img1, img2, label) in enumerate(train_loader):
            print(batch_idx)
            img1, img2, label = img1.to(device), img2.to(device), label.to(device)

            optimizer.zero_grad()

            emb1 = model(img1)
            emb2 = model(img2)

            loss = contrastive_loss(emb1, emb2, label)

            loss.backward()
            optimizer.step()

            running_loss += loss.item()

        # Average loss over the epoch
        epoch_loss = running_loss / len(train_loader)

        # Log to W&B
        wandb.log({"train/triplet_epoch_loss": epoch_loss})

        print(f"Epoch [{epoch+1}/{num_epochs}] - Triplet Loss: {epoch_loss:.4f}")

    end_time = time.time()
    print("Training completed!")

    return end_time - start_time



"""## Siamese Network: ResNet18 (baseline)"""

pretrained_path = 'resnet18_places365.pth.tar'
model = torchvision.models.resnet18(num_classes=365)

checkpoint = torch.load(pretrained_path, map_location='cpu')
state_dict = {str.replace(k,'module.',''): v for k,v in checkpoint['state_dict'].items()}
model.load_state_dict(state_dict)
model.eval()
print("")

train_transform = transforms.Compose([transforms.Resize((256,256)),
                      transforms.CenterCrop(224),
                      transforms.ToTensor(),
                      transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])

classes = list()
with open('IO_places365.txt') as class_file:
    for line in class_file:
        classes.append(line.strip().split(' ')[0][3:])
classes = tuple(classes)

image = Image.open('ocean.jpg')

image

image = train_transform(image).unsqueeze(0)
out = model(image)
_, pred = torch.max(out, dim = -1)
print(classes[pred.item()])

"""#### Model 1: Contrastive loss"""



"""#### Model 2:Triplet loss"""

class SiameseNeuralNetwork(torch.nn.Module):
    def __init__(self, feature_extractor):
        super().__init__()
        self.feature_extractor = feature_extractor

    def forward(self, image1, image2, image3):
        image1_feat = self.feature_extractor(image1)
        image2_feat = self.feature_extractor(image2)
        image3_feat = self.feature_extractor(image3)

        return image1_feat, image2_feat, image3_feat

class FeatureExtractorNetwork(torch.nn.Module):
    def __init__(self, pretrained_path='resnet18_places365.pth.tar'):
        super().__init__()

        # 1) Laad ResNet18 met 365 output klassen
        self.resnet = torchvision.models.resnet18(num_classes=365)

        # 2) Laad Places365 checkpoint
        checkpoint = torch.load(pretrained_path)
        state_dict = {k.replace('module.', ''): v for k, v in checkpoint['state_dict'].items()}
        self.resnet.load_state_dict(state_dict)


        self.resnet.fc = torch.nn.Linear(512, 1024)  # Double the size

    def forward(self, x):
        """Forward pass of the network."""
        x = self.resnet(x)
        return x









"""## Evaluation: n-way k-shot learning"""







"""## Explainable AI"""

